"""add daily_notes table

Revision ID: 3de614527061
Revises: 026cd3548404
Create Date: 2026-07-25 14:18:35.043846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de614527061'
down_revision: Union[str, Sequence[str], None] = '026cd3548404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'note_date', name='uq_daily_notes_user_date')
    )
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_notes_note_date'), ['note_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_notes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_notes_note_date'))

    op.drop_table('daily_notes')
    # ### end Alembic commands ###
