"""google calendar accounts and sources

Revision ID: eb1b4c51262c
Revises: b7c21a4d9e30
Create Date: 2026-08-09 01:15:11.180597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1b4c51262c'
down_revision: Union[str, Sequence[str], None] = 'b7c21a4d9e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_enc', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('calendar_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['calendar_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_sources_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_sources_account_id'))

    op.drop_table('calendar_sources')
    with op.batch_alter_table('calendar_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_accounts_user_id'))

    op.drop_table('calendar_accounts')
    # ### end Alembic commands ###
